//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _3D_Engine.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("_3D_Engine.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to # Blender v2.83.4 OBJ File: &apos;Arrow.blend&apos;
        ///# www.blender.org
        ///v -0.018473 -0.468012 0.960401
        ///v -0.043954 -1.113542 1.016396
        ///v -0.109423 -0.455415 0.960401
        ///v -0.260341 -1.083564 1.016396
        ///v -0.196167 -0.425317 0.960401
        ///v -0.466734 -1.011945 1.016396
        ///v -0.275373 -0.378874 0.960401
        ///v -0.655190 -0.901443 1.016396
        ///v -0.343997 -0.317872 0.960401
        ///v -0.818458 -0.756300 1.016396
        ///v -0.399401 -0.244654 0.960401
        ///v -0.950281 -0.582099 1.016396
        ///v -0.439456 -0.162033 0.960401
        ///v -1.045585 -0.385520 1.016396
        ///v -0.462623 -0.073 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Distant_Light {
            get {
                return ResourceManager.GetString("Distant_Light", resourceCulture);
            }
        }
    }
}
