//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _3D_Engine.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("_3D_Engine.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to v 0.083821 2.253639 0.116500
        ///v -0.083821 2.253639 0.116500
        ///v 0.083821 2.028270 0.138697
        ///v -0.083821 2.028270 0.138697
        ///v 0.083821 1.811561 0.204435
        ///v -0.083821 1.811561 0.204435
        ///v 0.083821 1.611841 0.311188
        ///v -0.083821 1.611842 0.311188
        ///v 0.083821 1.436786 0.454853
        ///v -0.083821 1.436786 0.454853
        ///v -0.083821 2.253640 -0.226717
        ///v 0.083821 2.253640 -0.226717
        ///v -0.083821 1.293122 -0.740123
        ///v 0.083821 1.293123 -0.740123
        ///v -0.083821 1.436787 -0.565068
        ///v 0.083821 1.436787 -0.565068
        ///v -0.083821 1.611843 -0.421403
        ///v 0 [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Camera {
            get {
                return ResourceManager.GetString("Camera", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to v -0.018473 -0.468012 0.960401
        ///v -0.043954 -1.113542 1.016396
        ///v -0.109423 -0.455415 0.960401
        ///v -0.260341 -1.083564 1.016396
        ///v -0.196167 -0.425317 0.960401
        ///v -0.466734 -1.011945 1.016396
        ///v -0.275373 -0.378874 0.960401
        ///v -0.655190 -0.901443 1.016396
        ///v -0.343997 -0.317872 0.960401
        ///v -0.818458 -0.756300 1.016396
        ///v -0.399401 -0.244654 0.960401
        ///v -0.950281 -0.582099 1.016396
        ///v -0.439456 -0.162033 0.960401
        ///v -1.045585 -0.385520 1.016396
        ///v -0.462623 -0.073186 0.960401
        ///v -1.100713 -0.174123 1.016396
        ///v -0.468012 0.01 [rest of string was truncated]&quot;;.
        /// </summary>
        public static string DistantLight {
            get {
                return ResourceManager.GetString("DistantLight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to v -3.000000 1.800000 0.000000
        ///v -2.991600 1.800000 -0.081000
        ///v -2.991600 1.800000 0.081000
        ///v -2.989450 1.666162 0.000000
        ///v -2.985000 1.921950 0.000000
        ///v -2.985000 1.921950 0.000000
        ///v -2.981175 1.667844 -0.081000
        ///v -2.981175 1.667844 0.081000
        ///v -2.976687 1.920243 -0.081000
        ///v -2.976687 1.920243 0.081000
        ///v -2.968800 1.800000 -0.144000
        ///v -2.968800 1.800000 0.144000
        ///v -2.958713 1.672406 -0.144000
        ///v -2.958713 1.672406 0.144000
        ///v -2.957600 1.534800 0.000000
        ///v -2.957600 1.534800 0.000000
        ///v -2.954122 1.915609 -0.144 [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Teapot {
            get {
                return ResourceManager.GetString("Teapot", resourceCulture);
            }
        }
    }
}
