//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using _3D_Engine.Enums;

namespace _3D_Engine.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.8.1.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Black")]
        public global::System.Drawing.Color EdgeColour {
            get {
                return ((global::System.Drawing.Color)(this["EdgeColour"]));
            }
            set {
                this["EdgeColour"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("LightBlue")]
        public global::System.Drawing.Color FaceColour {
            get {
                return ((global::System.Drawing.Color)(this["FaceColour"]));
            }
            set {
                this["FaceColour"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1000")]
        public float ShadowMapViewWidth {
            get {
                return ((float)(this["ShadowMapViewWidth"]));
            }
            set {
                this["ShadowMapViewWidth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1000")]
        public float ShadowMapViewHeight {
            get {
                return ((float)(this["ShadowMapViewHeight"]));
            }
            set {
                this["ShadowMapViewHeight"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10")]
        public float ShadowMapZNear {
            get {
                return ((float)(this["ShadowMapZNear"]));
            }
            set {
                this["ShadowMapZNear"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1000")]
        public float ShadowMapZFar {
            get {
                return ((float)(this["ShadowMapZFar"]));
            }
            set {
                this["ShadowMapZFar"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("81")]
        public float CameraWidth {
            get {
                return ((float)(this["CameraWidth"]));
            }
            set {
                this["CameraWidth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("64")]
        public float CameraHeight {
            get {
                return ((float)(this["CameraHeight"]));
            }
            set {
                this["CameraHeight"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10")]
        public float CameraZNear {
            get {
                return ((float)(this["CameraZNear"]));
            }
            set {
                this["CameraZNear"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("750")]
        public float CameraZFar {
            get {
                return ((float)(this["CameraZFar"]));
            }
            set {
                this["CameraZFar"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1000")]
        public float LightStrength {
            get {
                return ((float)(this["LightStrength"]));
            }
            set {
                this["LightStrength"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("30")]
        public int DirectionArrowResolution {
            get {
                return ((int)(this["DirectionArrowResolution"]));
            }
            set {
                this["DirectionArrowResolution"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10")]
        public float DirectionArrowBodyRadius {
            get {
                return ((float)(this["DirectionArrowBodyRadius"]));
            }
            set {
                this["DirectionArrowBodyRadius"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("20")]
        public float DirectionArrowTipRadius {
            get {
                return ((float)(this["DirectionArrowTipRadius"]));
            }
            set {
                this["DirectionArrowTipRadius"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10")]
        public float DirectionArrowBodyLength {
            get {
                return ((float)(this["DirectionArrowBodyLength"]));
            }
            set {
                this["DirectionArrowBodyLength"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("5")]
        public float DirectionArrowTipLength {
            get {
                return ((float)(this["DirectionArrowTipLength"]));
            }
            set {
                this["DirectionArrowTipLength"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("50")]
        public int AxisArrowResolution {
            get {
                return ((int)(this["AxisArrowResolution"]));
            }
            set {
                this["AxisArrowResolution"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10")]
        public float AxisArrowBodyRadius {
            get {
                return ((float)(this["AxisArrowBodyRadius"]));
            }
            set {
                this["AxisArrowBodyRadius"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("15")]
        public float AxisArrowTipRadius {
            get {
                return ((float)(this["AxisArrowTipRadius"]));
            }
            set {
                this["AxisArrowTipRadius"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("50")]
        public float AxisArrowTipLength {
            get {
                return ((float)(this["AxisArrowTipLength"]));
            }
            set {
                this["AxisArrowTipLength"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("100")]
        public float AxisArrowBodyLength {
            get {
                return ((float)(this["AxisArrowBodyLength"]));
            }
            set {
                this["AxisArrowBodyLength"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Verbosity.All")]
        public Verbosity Verbosity {
            get {
                return ((Verbosity)(this["Verbosity"]));
            }
            set {
                this["Verbosity"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("810")]
        public int CameraRenderWidth {
            get {
                return ((int)(this["CameraRenderWidth"]));
            }
            set {
                this["CameraRenderWidth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("640")]
        public int CameraRenderHeight {
            get {
                return ((int)(this["CameraRenderHeight"]));
            }
            set {
                this["CameraRenderHeight"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1000")]
        public int ShadowMapRenderWidth {
            get {
                return ((int)(this["ShadowMapRenderWidth"]));
            }
            set {
                this["ShadowMapRenderWidth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1000")]
        public int ShadowMapRenderHeight {
            get {
                return ((int)(this["ShadowMapRenderHeight"]));
            }
            set {
                this["ShadowMapRenderHeight"] = value;
            }
        }
    }
}
